-- Tactical sets: a third study kind. Flat collections of puzzles
-- (FEN + multi-ply solution line) authored by trainers and walked by
-- students. Attempts logged for progress; no spaced repetition.

CREATE TABLE IF NOT EXISTS tactic_set (
  id          BIGSERIAL PRIMARY KEY,
  owner_id    BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tactic_puzzle (
  id            BIGSERIAL PRIMARY KEY,
  set_id        BIGINT NOT NULL REFERENCES tactic_set(id) ON DELETE CASCADE,
  ord           INTEGER NOT NULL,
  fen           TEXT NOT NULL,
  solution_san  TEXT[] NOT NULL,
  comment_md    TEXT NOT NULL DEFAULT '',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_tactic_puzzle_set ON tactic_puzzle(set_id, ord);

CREATE TABLE IF NOT EXISTS tactic_attempt (
  id            BIGSERIAL PRIMARY KEY,
  user_id       BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  puzzle_id     BIGINT NOT NULL REFERENCES tactic_puzzle(id) ON DELETE CASCADE,
  correct       BOOLEAN NOT NULL,
  attempted_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_tactic_attempt_user_puzzle
  ON tactic_attempt(user_id, puzzle_id);

-- Extend the assignment.study_kind CHECK constraint to include 'tactic'.
-- The constraint name is generated by Postgres; we look it up by table
-- + column and drop it before re-adding.
DO $$
DECLARE
  cname TEXT;
BEGIN
  SELECT conname INTO cname
    FROM pg_constraint
   WHERE conrelid = 'assignment'::regclass
     AND contype = 'c'
     AND pg_get_constraintdef(oid) ILIKE '%study_kind%';
  IF cname IS NOT NULL THEN
    EXECUTE format('ALTER TABLE assignment DROP CONSTRAINT %I', cname);
  END IF;
  ALTER TABLE assignment
    ADD CONSTRAINT assignment_study_kind_check
    CHECK (study_kind IN ('opening','game','tactic'));
END$$;
